import { useQuery } from '@tanstack/react-query';
import { Clock3, LogIn, Phone, Search, Users } from 'lucide-react';
import { useState } from 'react';
import { getBlocks, getInside } from '../api/queries';
import { Loading } from '../components/common/Loading';
import { Visitor } from '../types';
function duration(value: string) { const minutes = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 60_000)); return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)} hr${minutes % 60 ? ` ${minutes % 60} min` : ''}`; }
function time(value: string) { return new Intl.DateTimeFormat('en-IN', { timeZone: 'Asia/Kolkata', hour: 'numeric', minute: '2-digit' }).format(new Date(value)); }
export function PeopleInside() { const [blockId, setBlockId] = useState(''); const blocks = useQuery({ queryKey: ['blocks'], queryFn: getBlocks }); const query = useQuery({ queryKey: ['admin-inside', blockId], queryFn: () => getInside(blockId || undefined), refetchInterval: 30_000 }); return <><div className="page-heading"><div><p className="eyebrow">LIVE OCCUPANCY</p><h2>People inside</h2><p className="muted">A live view of visitors who have not checked out yet.</p></div><div className="live-pill"><span className="live-dot"/>Live updates</div></div><div className="inside-toolbar"><div className="inside-total"><Users size={20}/><strong>{query.data?.length ?? 0}</strong><span>people currently inside</span></div><select value={blockId} onChange={(e) => setBlockId(e.target.value)}><option value="">All blocks</option>{blocks.data?.map((block) => <option key={block.id} value={block.id}>{block.name}</option>)}</select></div>{query.isLoading ? <Loading label="Loading current visitors..."/> : query.isError ? <div className="error-state"><h3>Live view unavailable</h3><button className="secondary-btn" onClick={() => void query.refetch()}>Try again</button></div> : query.data?.length ? <div className="inside-grid">{query.data.map((visitor) => <InsideCard visitor={visitor} key={visitor.id}/>)}</div> : <div className="empty-state panel"><div className="empty-icon"><LogIn size={22}/></div><strong>No visitors are currently inside</strong><span>Active visitors will appear here as they check in.</span></div>}</>; }
function InsideCard({ visitor }: { visitor: Visitor }) { return <article className="inside-card"><div className="inside-card-head"><div className="person-cell"><span className="person-avatar large-avatar">{visitor.visitorName.slice(0,1).toUpperCase()}</span><span><strong>{visitor.visitorName}</strong><small>{visitor.visitorCode}</small></span></div><span className="inside-label"><span className="live-dot"/>INSIDE</span></div><div className="inside-details"><span><Phone size={15}/>{visitor.phoneNumber}</span><span><LogIn size={15}/>Entered at {time(visitor.checkInAt)}</span><span><Users size={15}/>{visitor.block?.name}</span></div><div className="inside-card-foot"><span><Clock3 size={15}/>Inside for <strong>{duration(visitor.checkInAt)}</strong></span><span className="reason-text">{visitor.reasonForVisit}</span></div></article>; }
