import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import morgan from 'morgan';
import { corsMiddleware } from './config/cors';
import { sanitizeInput } from './middleware/sanitize';
import { errorHandler } from './middleware/errorHandler';
import { notFound } from './middleware/notFound';
import { authRoutes } from './modules/auth/auth.routes';
import { blockRoutes } from './modules/blocks/block.routes';
import { adminVisitorRoutes, watchmanVisitorRoutes } from './modules/visitors/visitor.routes';
import { adminDashboardRoutes, watchmanDashboardRoutes } from './modules/dashboard/dashboard.routes';
import { reportRoutes } from './modules/reports/report.routes';

export const app = express();
app.set('trust proxy', 1);
app.use(helmet());
app.use(corsMiddleware);
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: false, limit: '1mb' }));
app.use(cookieParser());
app.use(sanitizeInput);
app.use(morgan('tiny'));

app.get('/api/health', (_req, res) => res.json({ success: true, message: 'API is healthy' }));
app.use('/api/auth/admin', authRoutes('admin'));
app.use('/api/auth/watchman', authRoutes('watchman'));
app.use('/api/admin/dashboard', adminDashboardRoutes);
app.use('/api/admin/blocks', blockRoutes);
app.use('/api/admin/visitors', adminVisitorRoutes);
app.use('/api/admin/reports', reportRoutes);
app.use('/api/watchman/dashboard', watchmanDashboardRoutes);
app.use('/api/watchman/visitors', watchmanVisitorRoutes);
app.use(notFound);
app.use(errorHandler);
